### ISSUE TITLE
Whether leftDelim is covered by rightDelim

### ISSUE THREAD

**Issue by weiruizhang** [umakantp/jsmart-loader#3]
https://github.com/umakantp/jsmart-loader/blob/18a5833e3b518493a5900b212d24910ae646e8f5/index.js#L129

I think this should be ``rightDelim = query.rightDelim ``
Please help me.

**Comment by umakantp** [comment]
Sure. That's a bug, will fix and patch this today & release new version

**Comment by weiruizhang** [comment]
> Sure. That's a bug, will fix and patch this today & release new version. Thanks

thanks!
still have a question
There seems to be no place to configure template data

**Comment by umakantp** [comment]
sorry, can you please explain in more detail, what kinds of data you are not able to pass? May be you can explain with a example?

**Comment by umakantp** [comment]
Issue has been fixed. Please open new ticket, if you have new feature request. Thanks
